name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      run: |
        pytest fish_morphology_code/tests/

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 fish_morphology_code --count --verbose --max-line-length=127 --show-source --statistics
